CREATE DATABASE [SoftUni];

CREATE TABLE [Towns]
(
	[Id] INT PRIMARY KEY IDENTITY(1, 1),
	[Name] NVARCHAR(80) NOT NULL
)

CREATE TABLE [Addresses]
(
	[Id] INT PRIMARY KEY IDENTITY(1, 1),
	[AddressText] NVARCHAR(80) NOT NULL,
	[TownId] INT FOREIGN KEY REFERENCES [Towns] ([Id]) NOT NULL,
)

CREATE TABLE [Departments]
(
	[Id] INT PRIMARY KEY IDENTITY(1, 1),
	[Name] NVARCHAR(80) NOT NULL,
)

CREATE TABLE [Employees]
(
	[Id] INT PRIMARY KEY IDENTITY(1, 1),
	[FirstName] NVARCHAR(80) NOT NULL,
	[MiddleName] NVARCHAR(80) NOT NULL,
	[LastName] NVARCHAR(80) NOT NULL,
	[JobTitle] NVARCHAR(80) NOT NULL,
	[DepartmentId] INT FOREIGN KEY REFERENCES [Departments] ([Id]) NOT NULL,
	[HireDate] DATETIME2 NOT NULL,
	[Salary] DECIMAL(18,2),
	[AddressId] INT FOREIGN KEY REFERENCES [Addresses] ([Id]) NOT NULL
)