ALTER TABLE [Users]
DROP CONSTRAINT [PK_Users_Id_Username]

ALTER TABLE [Users]
ADD CONSTRAINT [PK_Users_Id] PRIMARY KEY ([Id])

ALTER TABLE [Users]
DROP CONSTRAINT [UQ__Users__536C85E407FC4D94]

ALTER TABLE [Users]
ADD CONSTRAINT [UQ_Username] UNIQUE ([Username])